name: Validate docs

on:
  workflow_dispatch:

jobs:
  lint-readme-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create temp directory
        run: mkdir -p temp

      - name: Extract JavaScript examples from README
        uses: firebolt-db/action-extract-doc-code@demo
        with:
          input_file: README.md
          language: typescript
          output_file: temp/extracted-code.ts
          block_number: 2 # Quickstart

      - name: Lint extracted examples
        run: npx eslint temp/extracted-code_block_1.ts

      - name: Clean up
        if: always()
        run: rm -rf temp
