name: PR checks

on:
  push:
    branches: [ main, 0.x ]
  pull_request:
    branches: [ main, 0.x ]

jobs:
  code-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Type check with typescript
        run: npm run type-check

      - name: Test with jest
        run: npm test -- --coverage test/unit

      - name: Upload coverage report
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: coverage
          path: coverage/
          retention-days: 1
